version: '2'
services:
  log:
    image: alpine
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./log/php-fpm:/var/log/php-fpm
    entrypoint: /bin/sh
  
  conf:
    image: alpine
    volumes:
      - ./vhosts:/etc/nginx/sites-available
    entrypoint: /bin/sh

  data:
    image: alpine
    volumes:
      - ./lib/mariadb:/var/lib/mariadb
      - ./lib/redis:/data
    entrypoint: /bin/sh

  application:
    image: alpine
    volumes: 
      - ./app:/app
    entrypoint: /bin/sh

  web:
    image: alexgkt/alpine-php
    container_name: web
    volumes_from:
      - log
      - conf
      - application
    ports:
      - "80:80"

  redis:
    image: redis:3.2:alpine
    container_name: redis
    volumes_from:
      - data
    ports:
      - "6379:6379"
    

  db:  
    image: mariadb
    container_name: mariadb
    volumes_from:
      - data
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

volumes:
  data:
  log:
  conf:
  application:
